### ISSUE TITLE
Sus dependency

### ISSUE THREAD

**Issue by JasonasIgn** [bahricanyesil/nodejs-starter-template#16]
What is this suspicious dev dependency? Can't find any info about this package. Could you explain what is this for?

package.json:
`"devDependencies": {
    "xxxxx": "^1.0.3"
  },`

**Comment by bahricanyesil** [comment]
Hi @JasonasIgn, it is most probably added mistakenly by [this commit](https://github.com/bahricanyesil/nodejs-starter-template/commit/897a19ec0d94278eb7da7c5e724156f2ef0121e0). Thanks for pointing it out. It doesn't mean anything and we should obviously remove that dependency.

**Comment by bahricanyesil** [comment]
I will update all dependencies and remove that one.

**Comment by JasonasIgn** [comment]
Thanks, I thought it could be some malicious library. Appreciate your fast response & awesome work on the starter!

**Comment by bahricanyesil** [comment]
Thank you for your nice thoughts. Thank you also for your review and for reporting the issue.

**Comment by bahricanyesil** [comment]
l created a PR and merged it as you can see: #17. If you don't have any additional comments and works fine on your local too, we can close the issue @JasonasIgn.

**Comment by bahricanyesil** [comment]
l created a PR and merged it as you can see: #17. If you don't have any additional comments and works fine on your local too, we can close the issue @JasonasIgn.
